spring.application.name=clothes
# C?u hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# connect to database
spring.datasource.url=jdbc:mysql://localhost:3306/db_clothesv1
spring.datasource.username=root
spring.datasource.password=123456
# JWT
app.jwt-secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwt-expiration-milliseconds=86400000