spring.application.name=clothes
# C?u hình Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# connect to database in railway
spring.datasource.url=jdbc:mysql://root:jnhwoyhgpzxtciwKuALzJsLCHerdOwgp@turntable.proxy.rlwy.net:13899/railway
spring.datasource.username=root
spring.datasource.password=jnhwoyhgpzxtciwKuALzJsLCHerdOwgp
# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration.access=900000
jwt.expiration.refresh=604800000
# send mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vuhoanghuy123321@gmail.com
spring.mail.password=yrrh sfdk irfx cxlt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
